version: '2'
services:
  webserver:
    build: ./docker/php
    links:
      - database
    ports:
     - "8081:80"
    volumes:
      - ./src/:/var/www/html
      - ./config/php/:/usr/local/etc/php/
  database:
    image: hypriot/rpi-mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: keinsicherespasswort
      MYSQL_USER: ComicDB
      MYSQL_PASSWORD: keinsicherespasswort
      MYSQL_DATABASE: ComicDB