version: '2'
services:
  webserver:
    build: ./docker/php
    links:
      - database
    ports:
     - "8081:80"
    volumes:
      - ./src/:/var/www/html
      - ./config/php/:/usr/local/etc/php/
  database:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: keinsicherespasswort
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # Init DB from backup
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - database:mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: keinsicherespasswort
