DROP DATABASE IF EXISTS ComicDB;
CREATE DATABASE ComicDB;
DROP USER IF EXISTS ComicDB;
CREATE USER ComicDB IDENTIFIED BY 'keinsicherespasswort';
GRANT ALL PRIVILEGES ON ComicDB.* TO ComicDB;

Use ComicDB;